name:
Parallel App Build Workflow
on
push ]
jobs
build
runs
on ubuntu latest
steps
-
run echo "Build
integration
testing
needs
build
runs
on: ubuntu latest
steps:
-
run echo "Integration
functional
testing
needs
build
runs
on: ubuntu latest
steps:
-
run echo "Functional
deploy
needs: [integration testing , functional testing]
runs
on: ubuntu latest
steps:
-
run echo "Deploy
